### ISSUE TITLE
Problem with Code Coverage Reporting

### ISSUE THREAD

**Issue by kenjis** [lonnieezell/CodeIgniter4#13]
Now I can't generate code coverage report.

~~~
[vagrant@localhost project]$ phpunit --colors --coverage-text=coverage.txt --coverage-html=coverage
PHPUnit 5.0.10 by Sebastian Bergmann and contributors.

...............................................................  63 / 272 ( 23%)
............................................................... 126 / 272 ( 46%)
............................................................... 189 / 272 ( 69%)
............................................................... 252 / 272 ( 92%)
....................                                            272 / 272 (100%)

Time: 15.86 seconds, Memory: 14.00Mb

OK (272 tests, 514 assertions)

Generating code coverage report in HTML format ...PHP Fatal error:  Cannot declare class CodeIgniter\PageNotFoundException, because the name is already in use in /mnt/project/system/Debug/CustomExceptions.php on line 49
PHP Stack trace:
PHP   1. {main}() /home/vagrant/.composer/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/vagrant/.composer/vendor/phpunit/phpunit/phpunit:47
PHP   3. PHPUnit_TextUI_Command->run() /home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:105
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:154
PHP   5. PHP_CodeCoverage_Report_HTML->process() /home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:486
PHP   6. PHP_CodeCoverage->getReport() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML.php:68
PHP   7. PHP_CodeCoverage_Report_Factory->create() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:144
PHP   8. PHP_CodeCoverage->getData() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Factory.php:24
PHP   9. PHP_CodeCoverage->addUncoveredFilesFromWhitelist() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:178
PHP  10. PHP_CodeCoverage->processUncoveredFileFromWhitelist() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:680
PHP  11. include_once() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:707

Fatal error: Cannot declare class CodeIgniter\PageNotFoundException, because the name is already in use in /mnt/project/system/Debug/CustomExceptions.php on line 49

Call Stack:
    0.0041     355592   1. {main}() /home/vagrant/.composer/vendor/phpunit/phpunit/phpunit:0
    0.0349    1003128   2. PHPUnit_TextUI_Command::main() /home/vagrant/.composer/vendor/phpunit/phpunit/phpunit:47
    0.0349    1003240   3. PHPUnit_TextUI_Command->run() /home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:105
    0.7600    4106488   4. PHPUnit_TextUI_TestRunner->doRun() /home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:154
   15.8625   10192872   5. PHP_CodeCoverage_Report_HTML->process() /home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:486
   15.8630   10192928   6. PHP_CodeCoverage->getReport() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML.php:68
   15.8650   10213464   7. PHP_CodeCoverage_Report_Factory->create() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:144
   15.8651   10213464   8. PHP_CodeCoverage->getData() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Factory.php:24
   15.8651   10213464   9. PHP_CodeCoverage->addUncoveredFilesFromWhitelist() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:178
   15.9923   10478424  10. PHP_CodeCoverage->processUncoveredFileFromWhitelist() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:680
   15.9972   10538168  11. include_once('/mnt/project/system/Debug/Exceptions.php') /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:707
~~~

This is because of the following `require`:

~~~diff
--- a/system/Debug/Exceptions.php
+++ b/system/Debug/Exceptions.php
@@ -35,7 +35,7 @@
  * @filesource
  */
 
-require dirname(__FILE__).'/CustomExceptions.php';
+require_once dirname(__FILE__).'/CustomExceptions.php';
 
 class Exceptions
 {
~~~

The above patch fixes the error but then it seems it shows debug bar and raise another error:

~~~
PHP Fatal error:  Uncaught Error: Call to undefined method PHP_CodeCoverage::renderTimeline() in /mnt/project/system/Debug/Toolbar/View/toolbar.tpl.php:38
Stack trace:
#0 /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(707): include_once()
#1 /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(680): PHP_CodeCoverage->processUncoveredFileFromWhitelist('/mnt/project/sy...', Array, Array)
#2 /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(178): PHP_CodeCoverage->addUncoveredFilesFromWhitelist()
#3 /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Factory.php(24): PHP_CodeCoverage->getData()
#4 /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(144): PHP_CodeCoverage_Report_Factory->create(Object(PHP_CodeCoverage))
#5 /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML.php(68): PHP_CodeCoverage->getReport()
#6 /home/vagrant/.composer/vendor/phpunit/phpunit in /mnt/project/system/Debug/Toolbar/View/toolbar.tpl.php on line 38

Fatal error: Uncaught Error: Call to undefined method PHP_CodeCoverage::renderTimeline() in /mnt/project/system/Debug/Toolbar/View/toolbar.tpl.php on line 38

Error: Call to undefined method PHP_CodeCoverage::renderTimeline() in /mnt/project/system/Debug/Toolbar/View/toolbar.tpl.php on line 38

Call Stack:
    0.0059     355592   1. {main}() /home/vagrant/.composer/vendor/phpunit/phpunit/phpunit:0
    0.0361    1003128   2. PHPUnit_TextUI_Command::main() /home/vagrant/.composer/vendor/phpunit/phpunit/phpunit:47
    0.0361    1003240   3. PHPUnit_TextUI_Command->run() /home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:105
    0.5748    4106488   4. PHPUnit_TextUI_TestRunner->doRun() /home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:154
   15.0706   10192872   5. PHP_CodeCoverage_Report_HTML->process() /home/vagrant/.composer/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:486
   15.0711   10192928   6. PHP_CodeCoverage->getReport() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML.php:68
   15.0756   10213464   7. PHP_CodeCoverage_Report_Factory->create() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:144
   15.0757   10213464   8. PHP_CodeCoverage->getData() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/Factory.php:24
   15.0757   10213464   9. PHP_CodeCoverage->addUncoveredFilesFromWhitelist() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:178
   15.3139   10653368  10. PHP_CodeCoverage->processUncoveredFileFromWhitelist() /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:680
   15.3232   10683384  11. include_once('/mnt/project/system/Debug/Toolbar/View/toolbar.tpl.php') /home/vagrant/.composer/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:707
~~~

**Comment by kenjis** [comment]
I was able to generate report. See #14 

~~~
Code Coverage Report:        
  2016-03-10 16:45:43        
                             
 Summary:                    
  Classes: 40.62% (26/64)    
  Methods: 39.49% (154/390)  
  Lines:   47.98% (1246/2597)
~~~
